apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjangoproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydjangoproject
  template:
    metadata:
      labels:
        app: mydjangoproject
    spec:
      containers:
      - name: mydjangoproject
        image: saadan12/mydjangoproject
        ports:
        - containerPort: 8000

# ---

apiVersion: v1
kind: Service
metadata:
  name: mydjangoproject
spec:
  selector:
    app: mydjangoproject
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: ClusterIP
